### ISSUE TITLE
Make Registry operator available on operatorhub.io and in Operator catalog

### ISSUE THREAD

**Issue by kadel** [devfile/api#1007]
## Which area this feature is related to?

/area registry

## Which functionality do you think we should add?
For ease of installation and to get some visibility Registry Operator should be available on https://operatorhub.io/

**Comment by kim-tsao** [comment]
Before we can make the operator available in the catalog, we will need to stabilize it first.  We made some major changes in the last few months to migrate the operator to newer k8s dependencies and re-worked the way the registry viewer gets deployed but it's caused some issues that we are still working through.  Once things are stabilize, we will need to ensure we have processes and test coverage to ensure we can update on a regular basis.  

These are some of the considerations that will apply to both artifacthub and operatorhub:

1. We will need to come up with a release process.  Currently one does not exist but once we cut one, we will consider releasing on a regular cadence TBD (either per quarter and/or driven by dependency updates whichever comes first).  Our plan is to support openshift 4.12+ in our first release

1. We need to ensure there's additional testing before publishing to the catalogs.  e.g. we do not have tests for the OLM bundles and I don't think we have integration tests with openshift.   We will probably need to add tests for Eclipse Che since they are another client that is interested in using the operator

**Comment by michael-valdron** [comment]
Additional investigation into the details of the pre-tasks needed to start working on the acceptance criteria. In particular, investigating what is needed for OLM support and publishing on the two catalogs.

Placing this issue under triage status.

**Comment by elsony** [comment]
We have an existing issue tracking adding the registry to the operator hub: https://github.com/devfile/api/issues/410
