### ISSUE TITLE
Add labels to metadata field

### ISSUE THREAD

**Issue by metacosm** [devfile/api#107]
**Is your feature request related to a problem? Please describe.**
Available metadata is current limited to version and name. Additional metadata in the form of `name:value` (or similar) labels or attributes would be helpful to categorize/search for devfiles. Such labels / attributes could be used to characterize the intent of the devfile (Che-focused vs. odo-focused vs. plugin, for example) and add information about the stack (runtime vs. app stem vs. service vs. …) so that tools could more easily ignore / focus on particular devfiles from a given registry.

**Describe the solution you'd like**
Adding more metadata to the metadata field :)

**Comment by sleshchenko** [comment]
duplicates https://github.com/devfile/api/issues/365

please reopen if I'm wrong.

**Comment by deboer-tim** [comment]
IMHO this should be reopened for discussion (I don't have access). #365 is specifically about being able to provide information in a devfile in order to set Kubernetes labels on the running container; this covers the more general case of providing labels or tags in order to search for or filter a list of devfiles.
