### ISSUE TITLE
Provide Mock Interface for Git Operations on devfile/library

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#1216]
/kind user-story

## Which area this user story is related to?

/area library

## User Story

As a client of devfile/library, I should be able to use mock implementation in devfile/library for the Git operations, either git CLI or a git API client.

For example, the git pkg https://github.com/devfile/library/tree/main/pkg/git provides various functions that either use git CLI or git API client. So the devfile/library should provide an interface implementation for these mock functions.

```
func NewGitClient() GitClient {
	return GitClient{}
}

func NewMockGitClient() MockGitClient {
	return MockGitClient{}
}

func (c GitClient) Clone() {}

func (c MockGitClient) Clone() {}

type GitFuncs interface {
	Clone()
}

type ParserArgs struct {
	 // Path is a relative or absolute devfile path.
	Path string
	...
	// Expose the Git Interface to able to use mock implementation.
	Git GitFuncs
	...
}

parserArgs := parser.ParserArgs{
	HTTPTimeout:                   &httpTimeout,
	Git: NewMockGitClient(), // Git: NewGitClient(),
}
```

## Acceptance Criteria

- [ ] Expose the Interface as part of the `ParserArgs`
- [ ] Mock implementation for all Git Cli/API operations
- [ ] Switch local tests to mock implementation

**Comment by kim-tsao** [comment]
Status Update:

When we download the main devfile in memory,  we perform a provider check (GitHub, GitLab, BitBucket)  on the URL.  If the host name matches, we construct a raw API and make a GET request using the raw API but we do not fail if the provided URL is not from a supported vendor.  We just make a GET request with the original URL i.e. there’s no processing of tokens and we just treat it like a public URL.  This seems like a bug but if I fix it, it’ll break all of our test cases because we set up HTTP test servers with localhost IPs.  I believe this has always been the behaviour since we have never validated git vendors in the past

In order to fix it, I would have to mock the DownloadInMemory function to handle non-git URLs but this function is called in the following cases 1) Setting the devfile content in context.Populate/PopulateURL - which would require mocking of these two methods as well 2) Converting K8s URI to inline and 3)  Reading the Kubernetes yaml for outerloop support, affecting our client usage.  
  
Since this is a lot of effort, I'll open a new issue to address this and use this issue to handle the following:

1. Expose the interface for mock testing parent URI references for external clients 
2. Remove duplicate util functions.  There are identical copies in the util and git packages and I believe this was done in order to avoid cyclic dependencies.  Rather than maintain two copies, I will refactor everything into one package (util) which  this may affect our clients if they use the util methods from the git package.  
3. Ensure git vendor validation is in place for parent URI references.  Similar to the main devfile scenario, we do not error out if absolute URL is not a supported git vendor
4. Fix test cases
