### ISSUE TITLE
Spike: Investigate CNCF Security Slam

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#1292]
/kind user-story

## Which area this user story is related to?

/area api
/area library
/area registry

## User Story

This Spike story is used to investigate the estimated time required for the CNCF work on Security Slam.

## Acceptance Criteria

- [x] Estimate how much time CNCF Security Slam witll take for Defender.

**Comment by maysunfaisal** [comment]
Defender Badge 

Requirements - https://github.com/devfile/api/discussions/1283

TODO

- [ ] Each project repo is accounted for within CLOMonitor (Need to update [clomonitor repo](https://github.com/cncf/clomonitor/blob/main/data/cncf.yaml) for other repos in the devfile project)
- [ ] Ensure proper check set is assigned to each project repo (List of check [here](https://clomonitor.io/docs/topics/checks/) and current assignment [here](https://github.com/cncf/clomonitor/blob/main/data/cncf.yaml))
- [ ] Bring security score to 100% for the project (To see a list of the Security related check runs that are available for each checks - refer [doc](https://clomonitor.io/docs/topics/checks/) and what action they entail refer [doc](https://clomonitor.io/docs/topics/checks/#security))

**Comment by maysunfaisal** [comment]
Cleaner Badge

Requirements - https://github.com/devfile/api/discussions/1283

TODO

- [ ] Bring all CLOMonitor non-security scores to 100% for the project like Best Practices, Documentation, License, Legal (List of check [here](https://clomonitor.io/docs/topics/checks/) and current assignment [here](https://github.com/cncf/clomonitor/blob/main/data/cncf.yaml))

**Comment by kim-tsao** [comment]
The Mechanizer Badge

Requirements - https://github.com/devfile/api/discussions/1283

To satisfy this requirement, we need to have an automated mechanism to publish our SBOMs upon every release.  The problem is, our [release process ](https://github.com/devfile/api/blob/main/docs/proposals/versioning-and-release.md#release-process) is on demand and because it's infrequent, we've been content with just running our scripts manually.


The webinar mentioned [goreleaser](https://goreleaser.com/) which automates the release process and can generate sboms.  This looks interesting and it is something we should look into since there is the potential it can be adopted by our other repos.  We can refer to this [example](https://github.com/kubernetes-sigs/bom/blob/main/.goreleaser.yml), which uses goreleaser.

TODO

- [ ] Investigate goreleaser as a replacement for our manual release process
- [ ] adopt goreleaser if it's a viable option

I've considered other alternatives like using one of the [recommended sbom generator tools](https://blog.sonatype.com/5-tools-to-automate-sbom-creation) to generate and upload an artifact in our CI workflow but this is not tied to our release process.  We may need to manually download the artifact and drop it whenever we cut a release so I don't think it will satisfy the badge requirements.  


Estimated Time:  ~3-4 weeks (assuming everything is straightforward with the investigation)
