### ISSUE TITLE
ODC support for devfile parent overrides

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1365]
## Which area/kind this issue is related to?

/area library

## Issue Description

There is an issue currently in the ODC side when someone is using a devfile that includes `parentOverrides`.

For example, someone can try to import https://github.com/devfile-samples/devfile-sample-go-basic/tree/v2.0.0. Its devfile overrides the build component and the console cannot import it.

As a result, this issue is focusing on the support of parent overrides on the [ODC](https://github.com/openshift/console) (Openshift Developer Console) side.

Main reason described [here](https://github.com/devfile/api/issues/1365#issuecomment-1834143198)

## Acceptance Criteria

- [ ] Communicate with ODC side, to pass URL + token instead of raw content to the backend.
- [ ] Issue https://github.com/devfile/api/issues/1136 should be completed and the latest library version should be pulled for ODC.
- [ ] Update the devfile handler in ODC backend to use the URL + token instead of the raw content ([here](https://github.com/openshift/console/blob/70a927c860c56bf63cf63f6ca2bbc87910ffdec6/pkg/devfile/handler.go#L52-L55)
- [ ] Test cases for parent and kubernetes uri reference should be added.

**Comment by yangcao77** [comment]
ODC used to send rawcontent to us, therefore the parent reference and kubernetes uri reference won't work due to devfile not flattened. 

But now library have the private repo support, we are ready to accept URL + token to parse the devfile content. 

So this issue needs to:
1. communicate with ODC team, let them to pass `URL + token` instead of rawcontent to backend. 
2. https://github.com/devfile/api/issues/1136 should pull in the latest library for ODC
3. update devfile handler in ODC backend to use the URL+ token instead of the rawcontent: 
https://github.com/openshift/console/blob/70a927c860c56bf63cf63f6ca2bbc87910ffdec6/pkg/devfile/handler.go#L52-L55
4. add some test cases for parent and perhaps kubernetes uri reference.

**Comment by yangcao77** [comment]
blocked by https://github.com/devfile/api/issues/1136

**Comment by thepetk** [comment]
> https://github.com/utherp0/hacexample repo only contains inner loop definition in the devfile, ODC only supports outerloop. so the first issue in the description is invalid.

I've updated the description!

**Comment by thepetk** [comment]
Definitely still a requirement

**Comment by thepetk** [comment]
Removing blocker label as the https://github.com/devfile/api/issues/1136 is now closed
