### ISSUE TITLE
Investigate and Add devfile repos to CLO Monitor

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#1371]
## Which area/kind this issue is related to?

N/A

## Issue Description

CLO Monitor report has a list of devfile repos that are being actively monitored. This list can be found in the file - https://github.com/cncf/clomonitor/blob/main/data/cncf.yaml#L521

Investigate what other devfile repos need to be added and update the file accordingly.

**Comment by Jdubrick** [comment]
I believe in order to have our major repositories covered by the CLO Monitor we should add the following to the file:

| Repository | Check Set |
|---|------|
| [Devfile-Web](https://github.com/devfile/devfile-web) | Code |
| [Alizer](https://github.com/devfile/alizer) | Code |
| [Registry-Operator](https://github.com/devfile/registry-operator) | Code|
| [Registry-Support](https://github.com/devfile/registry-support) | Code-Lite |

Additionally, currently on the CLO Monitor we have devfile library listed as `Code-Lite` and that should be changed to `Code` based on discussions in our meeting today for Devtools week. I believe Registry-Support however belongs as `Code-Lite` because it is primarily in a support role for other repositories. From referencing their [documentation](https://github.com/cncf/clomonitor/blob/main/docs/checks.md) I don't believe it is a primary project repository and more likely fits in with a secondary description.

@maysunfaisal what do you think?

**Comment by maysunfaisal** [comment]
I think devworkspace-operator, developer-images could be in the list as well.

**Comment by Jdubrick** [comment]
PR was opened on CLO Monitor repo - just waiting for approval and then all our repositories will be included and I will mark this issue as completed

**Comment by Jdubrick** [comment]
Repos were added to CLO Monitor, you can view them all here: https://clomonitor.io/projects/cncf/devfile
