### ISSUE TITLE
JSON Schema does not seem to be correctly configured for devfile

### ISSUE THREAD

**Issue by sleshchenko** [devfile/api#154]
**Describe the bug**
JSON schemas do not seem to work correctly for devfiles.

**To Reproduce**
Scenario with VSCode:
1. Open devfile/api with VSCode and install redhat yaml extension.
2. Open any sample and try to use competion:
it seems to be validated with devfile 1.x JSON Schema
![Screenshot_20201006_105520](https://user-images.githubusercontent.com/5887312/95174426-b82def00-07c2-11eb-88ad-b0851dd54f38.png)
![Screenshot_20201006_105532](https://user-images.githubusercontent.com/5887312/95174429-b8c68580-07c2-11eb-842f-3479576aa44a.png)
But competion combine devfile 1.x  + devfile 2.x variants
![Screenshot_20201006_105839](https://user-images.githubusercontent.com/5887312/95174576-ef040500-07c2-11eb-8992-bcf790d9a6c1.png)
![Screenshot_20201006_105851](https://user-images.githubusercontent.com/5887312/95174578-ef9c9b80-07c2-11eb-8442-44cdc2dd6329.png)

I assume it's caused by devfile 1.x schema that is accessible publicly somewhere and it wrongly configured.
So, we need to fix that configuration as well as start publishing devfile 2.x JSON Schema somewhere.

Che Workspace does not seem to validate devfile against devfile 1.x JSON Schema but completion does not work according to Devfile 2.x  JSON Schema 
![Screenshot_20201006_110201](https://user-images.githubusercontent.com/5887312/95174925-6174e500-07c3-11eb-933b-4986206f470b.png)

**Comment by JPinkney** [comment]
For some reason https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json#L716 is matching job-apply-example.devfile.yaml that's why the devfile 1.0 schema is coming through. The problem with statically configuring schemas through the schema store is that we technically run into an issue where two schemas (both the 1.0.0 devfile schema and the 2.0.0 devfile schema in this case) both apply to the same yaml name so theres no way to decipher between the two.

I've been working on a VSCode extension on the side though that will automatically set the schema for DevWorkspaceTemplates, DevWorkspace when it sees those inside of the YAML file so technically it solves that issue. However, it would technically only be available for any platform that supports the VSCode API

**Comment by davidfestal** [comment]
I assume that a temporary fix at least for the `devfile/api` repo devfile would be to add this option to the `devfile.api.code-workspace` and `.theia/settings.json` files 

```json
        "yaml.schemaStore.enable": false
```

**Comment by JPinkney** [comment]
Yeah for now disabling the schema store will work

**Comment by dgolovin** [comment]
Is there a way to manually configure URL for devfile 2.0.0 using YAML Language Server `yaml.schemas` settings?

**Comment by davidfestal** [comment]
> Is there a way to manually configure URL for devfile 2.0.0 using YAML Language Server `yaml.schemas` settings?

Yes, it is done here for example:
- https://github.com/devfile/api/blob/master/devfile.api.code-workspace#L20 for the vscode workspace
- https://github.com/devfile/api/blob/master/.theia/settings.json#L5 for Theia or Eclipse Che workspaces
