### ISSUE TITLE
Update docs with latest devfile.json

### ISSUE THREAD

**Issue by mmulholla** [devfile/api#174]
Doc is currently using an out of date devfile.json. It does not include the change which made component required for exec and apply commands. 

Also we need a process defined for keeping it current.

**Comment by davidfestal** [comment]
Since I added automatic geenration of the api-reference doc in the docs repo, the only thing to do in order to have the docs updated is to update the content of this `docs` file:

https://github.com/devfile/docs/blob/master/docs/modules/ROOT/attachments/jsonschemas/next/devfile.json

with the last content of this `api` file:

https://github.com/devfile/api/blob/master/schemas/latest/devfile.json

Ideally, this should be done automatically through a GitHub action when a commit is pushed to the `master` branch of the `devfile/api` repository. I started looking at this recently, but didn't implement it for now.

**Comment by davidfestal** [comment]
> Since I added automatic geenration of the api-reference doc in the docs repo, the only thing to do in order to have the docs updated is to update the content of this `docs` file:
> 
> https://github.com/devfile/docs/blob/master/docs/modules/ROOT/attachments/jsonschemas/next/devfile.json
> 
> with the last content of this `api` file:
> 
> https://github.com/devfile/api/blob/master/schemas/latest/devfile.json
> 
> Ideally, this should be done automatically through a GitHub action when a commit is pushed to the `master` branch of the `devfile/api` repository. I started looking at this recently, but didn't finish implementing it for now.

Done in linked PR
