### ISSUE TITLE
Discussion: Which License should devfile/api use?

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#212]
Currently devfile/api is using EPL license: https://github.com/devfile/api/blob/master/LICENSE

And consumers like odo and console are using Apache. 

EPL license has strong copyleft, while Apache is more permissive. 
with EPL, it ensures people are not using it to make profit; however, any derivative works must also be with EPL as well. 
 https://www.apache.org/licenses/GPL-compatibility.html

> This licensing incompatibility applies only when some Apache project software becomes a derivative work of some GPLv3 
software, because then the Apache software would have to be distributed under GPLv3. This would be incompatible with ASF's requirement that all Apache software must be distributed under the Apache License 2.0.

> We avoid GPLv3 software because merely linking to it is considered by the GPLv3 authors to create a derivative work. 

and that is why odo is blacklisting vendors with GPL

IMO, devfile/api should use Apache. Any particular reason why we use EPL for devfile/api?
Same question to devworkspace

**Comment by maysunfaisal** [comment]
I would also recommend this YouTube video on open source copyrights as a good guide to understanding the differences between copyleft and permissive licenses. You can start from 14:28 https://youtu.be/OnmWFxlG2GA?t=868

**Comment by elsony** [comment]
> EPL license has strong copyleft, while Apache is more permissive.

EPL is actually a weak copyleft, not strong copyleft. GPL is the one that we try to avoid. The link that you provide is for GPL. I think the main reason that the current license is using EPL is because devfile was originated from devfile 1.0 which is part of Che and Che is using EPL license. Many of the Eclipse project is using EPL. Given that we haven't decide which foundation we are going to park this project (EPL is the default license for Eclipse projects), I don't see a problem with staying on EPL for the time being.

**Comment by yangcao77** [comment]
So sounds like odo should whitelist EPL-2.0?
