### ISSUE TITLE
Improve devfile library test 

### ISSUE THREAD

**Issue by elsony** [devfile/api#215]
Existing devfile library have limited test on the parser. This item will improve the existing library test to provide a more comprehensive test.

**Comment by mmulholla** [comment]
Test of Library api's
- [ ] Commands
  - [ ] Apply 
  - [x] Exec
  - [x] Composite
  - [ ] Project
  - [ ] Starter Project
  - [ ] VsCodeTask  
  - [ ] VSCodeLaunch
- [ ] Components
  - [x] Container
  - [ ] Kubernetes
  - [ ] Openshift
  - [ ] Plugin
  - [x] Volumes
- [ ] Events
- [ ] MetDatada
- [ ] Projects
- [ ] StarterPorjects
- [ ] VSCodeLaunch
- [ ] VSCodeTask
- [ ] API errors

Test of schema parsing
- [ ] All attributes and errors

**Comment by mmulholla** [comment]
@elsony My plan is to open a new issue for each function as I add it and add a link to the table. You may want to add priorites to the table. Also need to understand what the parser supports.

**Comment by kim-tsao** [comment]
We can use the code coverage reports (once in place) to correlate what's missing: https://github.com/devfile/api/issues/470

**Comment by kim-tsao** [comment]
https://github.com/devfile/api/issues/215#issuecomment-849815483 is only relevant to the unit tests we have which I've captured in another issue https://github.com/devfile/api/issues/489

When this issue was first opened, it was intended to capture updating the tests with respect to version 2.0.0.  Since then, we've had v2.1.0 and v2.2.0 which introduced new changes.  I will open a new issue to track updating these tests to the new spec levels.

**Comment by kim-tsao** [comment]
The remaining tests for error scenarios will be tracked by epic: https://github.com/devfile/api/issues/1100
