### ISSUE TITLE
Basic registry access function library

### ISSUE THREAD

**Issue by elsony** [devfile/api#224]
Provide a go library to provide APIs that allow tools to interact with a devfile registry to:
- [x] Get the registry index of a given registry
- [x] Get the devfile that belongs to a given stack
- [x] Get the devfile + the containing stack resource files of a given stack

**Comment by GeekArthur** [comment]
Based on our discussion. this is the workflow of client library:
client library -> ORAS package -> index server (location /v2) -> registry

**Comment by GeekArthur** [comment]
Links index server REST APIs PRs below to this issue as registry library also needs the index server REST APIs:
1. Index server REST APIs docs: https://github.com/devfile/api/pull/282
2. Index server REST APIs implementations: https://github.com/devfile/registry-support/pull/17

**Comment by johnmcollier** [comment]
@GeekArthur How do you plan on the registry handling errors? Will it try only once and error out if an error occurs or will it re-try?

**Comment by GeekArthur** [comment]
> @GeekArthur How do you plan on the registry library handling errors? Will it try only once and error out if an error occurs or will it re-try?

Can you specify what kind of errors? For example, the errors are validation errors from parsing or errors from use ORAS to pull down the stack resources? I think we may use different ways to handle different errors.

Currently for all kinds of errors we only try once, but we can use retry mechanism with retry times limitation or timeout for errors that related with network so that we can rule out the temporary network issue.
