### ISSUE TITLE
Seperate v1 and v2 generated files (eg. generated crd files)

### ISSUE THREAD

**Issue by GeekArthur** [devfile/api#247]
**Describe the bug**
Currently in our `build.sh` script we have this line `generator/build/generator "crds" "output:crds:artifacts:config=crds" "paths=./pkg/apis/workspaces/v1alpha2;./pkg/apis/workspaces/v1alpha1"`, I think that line means we run v1alpha1(v1) generator source code after v1alpha2(v2) generator source code, then we have the cases below:
1. Generator source code of v1 and v2 are identical -> no affect
2. Generator source code of v1 and v2 are different -> v1 has higher priority as finally v1 overrides v2

**To Reproduce**
1. Run `build.sh`
2. Then new feature in v2 generator (shorname from this PR: https://github.com/devfile/api/pull/209) can't take effect in our generated crd files

**Expected behavior**
The generator is supposed to generate both v1 and v2 code and put the generated code in the corresponding folders that matches the version.

**Comment by amisevsk** [comment]
CRDs are supposed to contain all versions of a custom resource spec, e.g.
```
$ cat crds/workspace.devfile.io_devworkspaces.yaml | yq '.spec.versions[].name'
"v1alpha1"
"v1alpha2"
```
splitting CRDs into two files based on version is incorrect and would break conversion webhooks.

**Comment by GeekArthur** [comment]
> CRDs are supposed to contain all versions of a custom resource spec, e.g.
> 
> ```
> $ cat crds/workspace.devfile.io_devworkspaces.yaml | yq '.spec.versions[].name'
> "v1alpha1"
> "v1alpha2"
> ```
> 
> splitting CRDs into two files based on version is incorrect and would break conversion webhooks.

That's a good point, if we already had the mechanism of separating versions, we can still use the existing mechanism to avoid breaking changes. From this PR https://github.com/devfile/api/pull/209, seems like the new devworkspaces shortname feature should apply to both v1alpha1 and v1alpha2 as from `workspace.devfile.io_devworkspaces.yaml` the shortname field doesn't fall down to versions. Then probably the easy fix is just add this line `// +kubebuilder:resource:path=devworkspaces,scope=Namespaced,shortName=dw` to `v1alpha1/devworkspace_types.go`

**Comment by amisevsk** [comment]
I think keeping them in sync may be necessary (it makes sense to do so generally, anyways). Poking into the code a bit, it looks as though this behaviour is coming from controller-tools: `NeedCRDFor()` goes through versions and [applies markers](https://github.com/kubernetes-sigs/controller-tools/blob/895eccc97eb59b9973a8b610e6ed6a2fc5a5a6d3/pkg/crd/spec.go#L102-L121) to the CRD, and for Resources, it does no merging -- `shortNames` is set to whatever is in the marker for the current package, even if that [value is empty](https://github.com/kubernetes-sigs/controller-tools/blob/895eccc97eb59b9973a8b610e6ed6a2fc5a5a6d3/pkg/crd/markers/crd.go#L286). From what I can tell the order in which versions are processed can't be controlled (it's sorted to avoid potential changes between runs due to order).

**Comment by davidfestal** [comment]
I started working on a simple fix in the generator to avoid having to keep the shortnames in sync in the various apiVersion packages. Will open a PR soon.

**Comment by elsony** [comment]
@davidfestal Given that PR #273 has been merged, is there any outstanding work on this item? Can we close off this item?

**Comment by davidfestal** [comment]
Seems we can close it

**Comment by elsony** [comment]
Done
