### ISSUE TITLE
Fix Adding commands to a devfile

### ISSUE THREAD

**Issue by themr0c** [devfile/api#253]
In https://docs.devfile.io/devfile/2.0.0/user-guide/adding-commands-to-a-devfile.html

* Add `composite` in the list of allowed types.
* rename the current example as "an `exec` command", add an example for  a `vscode-tasks` command. 
* reorganize in subpages as for components: Adding `exec` command, Adding `vscode-tasks` command, Adding `composite` command, Adding command in a group.
* `previewUrl` seems to belong to the `exec` command description.

**Comment by rkratky** [comment]
JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2566

**Comment by jc-berger** [comment]
Are the concerns laid out in this issue still relevant?

**Comment by jc-berger** [comment]
Here's a checklist of what we've done for these concerns:

- [] Add composite in the list of allowed types.

- [ ]  rename the current example as "an exec command", add an example for a vscode-tasks command.

- [ ] reorganize in subpages as for components: Adding exec command, Adding vscode-tasks command, Adding composite command, Adding command in a group.

- [ ] previewUrl seems to belong to the exec command description.

**Comment by elsony** [comment]
> * Add `composite` in the list of allowed types.
Already have info on `composite` command in the current doc
> * rename the current example as "an `exec` command", add an example for  a `vscode-tasks` command.
We have removed `vscode-tasks` so this no longer applies. One thing that I note is we still have one reference to the `vscode-tasks` so we should remove that reference.
> * reorganize in subpages as for components: Adding `exec` command, Adding `vscode-tasks` command, Adding `composite` command, Adding command in a group.
This can still be valid since we currently just have a flat list of steps. It can be organized by adding different sections of the command.
> * `previewUrl` seems to belong to the `exec` command description.
This is no longer in the spec, no longer applicable
