### ISSUE TITLE
Inconsistent devfile docs wrt schema 2.x.x

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#314]
I have glanced through the devfile docs and found inconsistencies wrt devfile schema 2.x.x. Perhaps these are from devfile schema 1.x.x?

## projects

1. Schema has no location and branch for git
![Screen Shot 2021-01-19 at 12 48 28 PM](https://user-images.githubusercontent.com/31771087/105073171-b7a92380-5a54-11eb-897f-58885324bb44.png)

2. Schema has no tag, commitId, branch
![Screen Shot 2021-01-19 at 12 50 25 PM](https://user-images.githubusercontent.com/31771087/105073357-f808a180-5a54-11eb-8995-d8264bef59da.png)

### plugin

plugin component has no preferences
![Screen Shot 2021-01-19 at 1 00 20 PM](https://user-images.githubusercontent.com/31771087/105074529-79acff00-5a56-11eb-91d3-f63e3d02576c.png)

### kubernetes

kubernetes component has no selector, reference, reference content, entrypoint, etc
![Screen Shot 2021-01-19 at 1 08 00 PM](https://user-images.githubusercontent.com/31771087/105075209-72d2bc00-5a57-11eb-86c2-be029db217ef.png)

### storage

persistent storage (vol mount)cannot be specified via kubernetes/openshift except for container
![Screen Shot 2021-01-19 at 1 12 02 PM](https://user-images.githubusercontent.com/31771087/105075648-04dac480-5a58-11eb-88ad-151fab24fa84.png)

You will need to have a volume component to specify storage

### env

plugin cannot mention env in its spec
![Screen Shot 2021-01-19 at 1 13 48 PM](https://user-images.githubusercontent.com/31771087/105075817-43707f00-5a58-11eb-9ee9-5b5c5b2e1eff.png)

### endpoints

plugin cannot define endpoints like this 
![Screen Shot 2021-01-19 at 1 15 32 PM](https://user-images.githubusercontent.com/31771087/105075961-7155c380-5a58-11eb-8ab2-b0cbb72a4b7a.png)

### exec

exec command does not have run as root spec

![Screen Shot 2021-01-19 at 1 17 52 PM](https://user-images.githubusercontent.com/31771087/105076242-ce517980-5a58-11eb-8c6f-8f905f036a57.png)

exec has no preview url spec
![Screen Shot 2021-01-19 at 1 21 03 PM](https://user-images.githubusercontent.com/31771087/105076605-415af000-5a59-11eb-8f32-725964f7a9a5.png)

**Comment by mmulholla** [comment]
see: https://github.com/devfile/api/issues/311

**Comment by rkratky** [comment]
JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2557

**Comment by jc-berger** [comment]
@maysunfaisal, thanks, Maysun for pointing this out. In my PR, I've addressed these concerns and have kept an eye out for similar errors in our other docs. Mostly, I've modified the source.yaml. A lot of what I did was omitting outdated content from the source.yaml, so we'll need to ensure that the source.yaml still makes sense. 


Specifically for the doc, `adding kubernetes components to a devfile`, I wonder how much of this doc is still relevant? To my understanding, kubernetes no longer has a selector, reference, reference content,  nor entrypoint. Since the bulk of kubernetes content in this doc is based off kubernetes having these components, won't the majority of the doc have to go? After editing the source.yaml, I was stumped as to what to do for the instructions because they all were based around, "adding kubernetes using reference" etc. I wanted to get a second opinion before removing more content. 

Thanks! 

https://github.com/devfile/docs/pull/43
