### ISSUE TITLE
Make vscodeLaunch / vscodeTask more generic

### ISSUE THREAD

**Issue by benoitf** [devfile/api#344]
**Is your feature request related to a problem? Please describe.**
It seems that vscodeLaunch and vscodeTask are not generic enough and then I'm not sure it belongs to devfile API spec.

**Describe the solution you'd like**
Get rid of it but allow to use them with annotations or with a more generic approach like 'name of file to add or key' and the content of the inlined content

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sunix** [comment]
in all of the devfiles we have in Che, we only use vscode-launch to define the debug mode. In all the other use case, we are using commands-actions from devfile v1. This format has been there for since Che6 so used in the old GWT IDE and now consumed by Che-Theia. So I suggest we should consider having something similar when it is to define the debug configuration.

**Comment by tsmaeder** [comment]
You mean a mechanism like I described in https://github.com/eclipse/che/issues/15518#issuecomment-598104173 ? Writing files to disk is fine, but we should take care to use intermediate formats that can be interpreted by glue code, not directly bake the structure of the workspace. Otherwise, we'll run into problems like https://github.com/eclipse/che/issues/17975 in the future again.

**Comment by tsmaeder** [comment]
Wouldn't simply allowing free-form attributes on the proper devfile objects allow to attach any kind of IDE-specific configuration to those objects? We would simply have to establish a scheme to avoid key collisions.

**Comment by elsony** [comment]
We'll remove the vscodeLaunch and vscodeTask from the devfile 2.x spec. Tools can use annotation with the attributes field under the projects/metadata section to specify IDE specific info.
