### ISSUE TITLE
What is globalMemoryLimit?

### ISSUE THREAD

**Issue by kadel** [devfile/api#361]
There is a `metadata.globalMemoryLimit`, with the description "Optional devfile global memory limit".

How should tools interpret this?

Is this memory limit just for `container `components? What about `kubernetes` components? 

 Is it the sum of the memory limits of all containers or every container should have this limit. if `globalMemoryLimit: 8G` does it mean that each container will have 8GB limit, or sum of their limits will be 8G?

What if there are conflicting values in `globalMemoryLimit` and `container.MemoryLimit`

**Comment by elsony** [comment]
The `GlobalMemoryLimit` was inherited from devfile 1.0 metadata.yaml. Based on the description in https://www.eclipse.org/che/docs/che-7/administration-guide/building-custom-registry-images/, it is supposed to be "The sum of the expected memory consumed by all the components launched by the devfile. This number will be visible on the user dashboard. It is informative and is not taken into account by the Che server." 

As @kadel pointed out, `container` components already have a `memoryLimit` settings. Do we still need this global memory limit? What if the total of all the container `memoryLimit` exceeds the `GlobalMemoryLimit`? Will that create inconsistency between settings within the same devfile. 

@l0rd @davidfestal Do we still need to `GlobalMemoryLimit` under the metadata section given that we already have memory settings in individual containers? Based on the description, Che is using it to display on the dashboard, is it something that we can calculate by adding the memory limits in all containers instead of explicitly set in the metadata?

**Comment by l0rd** [comment]
Metadata are exposed by the devfile registry and consumed by clients (`che`, `odo`) before requesting the corresponding devfile. 

`GlobalMemoryLimit` is supposed to correspond to the sum of the components `MemoryLimits`. That is useful for `Che` or `odo` to evaluate if the memory available on the cluster is sufficient to run a given stack. If it's not we may hide that particular stack to users.

That said `GlobalMemoryLimit` may disappear from the devfile spec if on the registry side we have another mechanism to expose exposite (for example automatically compute the sum of the components `MemoryLimits` when a devfile is published).

**Comment by kadel** [comment]
> `GlobalMemoryLimit` is supposed to correspond to the sum of the components `MemoryLimits`. That is useful for `Che` or `odo` to evaluate if the memory available on the cluster is sufficient to run a given stack. If it's not we may hide that particular stack to users.

And what if doesn't correspond to sum of the memorylimits? 

If it is only used to filter out stacks what is preventing me from creating devfile with `globalMemoryLimit: 1MiB`  and then having containers use more?

This field should not be in devfile. It can be easily calculated. 



> That said `GlobalMemoryLimit` may disappear from the devfile spec if on the registry side we have another mechanism to expose it (for example automatically compute the sum of the components `MemoryLimits` when a devfile is published).

+1
