### ISSUE TITLE
Devfile library used by odo rewrites properties in alphabetical order upon save/write rather than preserving original order upon read.

### ISSUE THREAD

**Issue by scottkurz** [devfile/api#371]
**Describe the bug**

Using odo v2.0.6, functions which rewrite the devfile.yaml will write its properties in alphabetical order rather than preserving the original order.   I'm not saying any semantics are broken, but it's just inconvenient to look in Git and see a more complicated change history because of this reordering.

**To Reproduce**
1. With a recent odo (e.g. v2.0.6)
2. git clone https://github.com/OpenLiberty/application-stack-intro.git && cd application-stack-intro
3. odo create c1
4. odo config set --env foo=bar
5. git diff

**Expected behavior**
The `git diff` ideally should show a small delta to **devfile.yaml** with the 'env' added.   Instead I see a bigger diff, mainly because my devfile follows the pattern in the devfile/registry of using the ordering:   **schemaVersion, metadata, starterProj, components, commands**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by yangcao77** [comment]
This is an issue with golang standard pkg: `encoding/json`, it does a sort during `json.Unmarshal`. (https://golang.org/src/encoding/json/encode.go?#L1334)

The order cannot be preserved. They raised up a commit to preserve the order, but eventually abandoned it:https://go-review.googlesource.com/c/go/+/7930

The commiter (Peter Waldschmidt) made a copy of that code in this repo: https://github.com/virtuald/go-ordered-json, but that is discouraged to be used, as they said it's "contrary to the [JSON specifications](https://www.ietf.org/rfc/rfc4627.txt)", since order does not matter in JSON.

**Comment by yangcao77** [comment]
Further investigation, try to avoid using `encoding/json` and use yaml package to marshal & unmarshal devfile content?

Not going to work. The yaml package library & dev-workspace use is: [sigs.k8s.io/yaml](https://pkg.go.dev/sigs.k8s.io/yaml)
It is a yaml package used by Kubernetes. 
However, that yaml package uses `encoding/json` to marshal & unmarshal. (https://github.com/kubernetes-sigs/yaml/blob/11e43d4a8b9271a822a950dbf9b6ff15fe00fafc/yaml.go#L17). So json encoding/decoding is not avoided, and will get the same result. 

We intentionally switched to use `sigs.k8s.io/yaml`  instead of `gopkg.in/yaml.v2`, since the yaml package from Kubernetes does not require yaml tags in structs, and makes sense to use the yaml package that's used in the rest of Kubernetes, as most k8s objects only have json tags, as suggested in https://github.com/devfile/api/pull/203#issuecomment-724981014


Conclusion: It's not something can be easily resolved from library level. As long as needs to marshal/unmarshal the devfile content, it will go through the golang basic library `encoding/json`; which does the sort by field names (https://golang.org/src/encoding/json/encode.go?#L1334)

**Comment by kadel** [comment]
What if we make sure that all devfiles in devfile registry have keys sorted alphabetically? 
I know that it is not an ideal solution, but it would make the diffs a little bit nicer.

**Comment by yangcao77** [comment]
@elsony @johnmcollier @GeekArthur  Any thoughts?

**Comment by elsony** [comment]
Given that we can't find a solution to that, sorting them alphabetically for all the devfiles in the registry is probably our best choice at this point.

**Comment by scottkurz** [comment]
The problem would look a lot different if, on `odo create java-openliberty mycomponent`, I got an almost-empty stub referencing the java-openliberty devfile as a parent.    The problem is that it's harder to manually edit that syntax and get the parent override correct without tools. ...but maybe odo makes it easy enough.    (And maybe this is getting too specifically tied into the odo case.)

**Comment by kadel** [comment]
I agree that manual edits are going to be a pain :-(  But I'm afraid that currently, it is just picking what will cause less pain :/ 

Option 1: Nicely formatted devfiles in the registry, that are easy to manually edit, but as soon as you use odo (or any other tool that is not text editor) to modify the devfile, it will make an ugly diff.

Option 2: Alphabetically sorted keys in registry devfiles, that are harder to edit manually, but will produce nice diff if edited programmatically.


The decision depends on how we think the devfiles will be used. If we assume that normal users (not stack/devfile creators) will mostly use tools like odo and don't touch devfile.yaml directly than option 2 makes more sense. 

But if we assume that most of the users will want to edit devfile.yaml manually than option 1 makes more sense.

The problem is that odo works with the assumption that the user shouldn't need to touch devfile.yaml but Che mostly assumes that if the user needs to add something into devfile, he/she will edit it directly in IDE.

**Comment by feloy** [comment]
You could also consider having 2 files.

- A file that is human-readable, with fields ordered in a specific order different than the alphabetic one, that makes the file easy to read for a human.

- The generated file with the fields alphabetically ordered. 

The hard part becomes to keep in sync these 2 files when the user modifies its file or the library modifies the generated one.

For example, you could save only the generated one, and when the user wants to edit it, you first create a copy of the file with the fields reordered in a user-friendly way, then when the user saves the file, you create a generated version of the file the user edited.
 
As an inspiration, this vscode extension provides a way to order a yaml file in different user-defined orders: https://marketplace.visualstudio.com/items?itemName=PascalReitermann93.vscode-yaml-sort

**Comment by kadel** [comment]
hi @feloy 😉 

I'm afraid that keeping the same file in two different formats is going to create more problems.

>  As an inspiration, this vscode extension provides a way to order a yaml file in different user-defined orders: https://marketplace.visualstudio.com/items?itemName=PascalReitermann93.vscode-yaml-sort

This is interesting. I did not know about this before. We could have our own custom sorting order for devfiles. 
It won't solve the problem where keys are re-ordered after odo edits the file, but at least it would keep the devfile structure in some sensible way.

**Comment by elsony** [comment]
> The problem is that odo works with the assumption that the user shouldn't need to touch devfile.yaml but Che mostly assumes that if the user needs to add something into devfile, he/she will edit it directly in IDE.

I think we'll see more use case/tools in the future that tools will be editing the devfile for the user, e.g. I can see in the future that someone can bind a service to an app using the dev console UI and that eventually may be translated to writing the service binding info back to the devfile. 

And it is interesting to know that there are existing tools that do custom sorting orders. @yangcao77 Can you investigate that to see if it is something that we can use (or do something similar) in our library.

**Comment by yangcao77** [comment]
I don't think we can use that existing tools (it is nodejs), or do something similar, as the logic behind that tool does not fulfill our requirement. 

Our requirement: preserve the existing fields order in devfile.yaml
which requires read&unmarshal to get the order, and then marshal&write with correct order

The vscode re-order tool's requirement: marshal&write with pre-defined order, the original order does not matter. 
and to write in order, the tool did not use js standard encoding library to marshal&write; they created their own logic to reorganize the content in yaml format


Library need to unmarshal the devfile content into devfile struct defined in devfile/api. by that time the field order has been already sorted by json/encoding, and cannot get the original order

**Comment by maysunfaisal** [comment]
The current plan is to avoid using the golang modules that rewrite YAMLs/JSONs alphabetically on UnMarshal/Marshal calls

- [ ] Read the devfile during unmarshalling to preserve original order
- [ ] Access the original order when marshalling and writing to a file

(Tip: Second checklist can be started first by assuming a pre-determiend order before tackling the first checklist)
