### ISSUE TITLE
Proposal for new top-level documentation structure

### ISSUE THREAD

**Issue by robin-owen** [devfile/api#441]
Creating this issue as a place to discuss and reference a large restructure of both new and existing documentation content for the Devfile documentation site. This information is based on a proposed table of contents shared by @rkratky in https://github.com/devfile/docs/pull/54 (Restructure site for multiple sets of documentation).

Proposed structure:

- Getting Started with Devfiles
  - What are devfiles?
  - How devfiles works?
  - Quick Start Guide
  - Devfile samples
  - Tools using Devfiles
- Using Devfiles
  - Using existing devfiles
  - Building a devfile for your project
  - Contributing a devfile to the community
- Using Devfile Registry
  - ...
- Using Devfile Library
  - ...

@elsony also proposed the following (https://github.com/devfile/docs/pull/54#issuecomment-825081196):

> Instead of dividing into using devfiles, using registry, using library, it will be nice if we present those under different persona instead of the technology area, e.g. application developer, architects (stack/sample providers), registry administrator, tools provider, etc., and then put the individual technology-specific info under each persona. If we organize that way, we can also talk about the problems, benefits, values, and use cases for each persona for them to understand how devfile can help them in each case.

The above is an excellent point that we should keep in mind as we discuss the desired structure and come to a consensus.

**Comment by jc-berger** [comment]
Looking at the proposed structure, I assume our current "overview" would go under `what are devfiles?` and/or `how devfiles work`. I'm thinking our current authoring stacks would go under `quick start guide` and/or `devfile samples` because the authoring stacks' purpose is to add features to devfiles and get up and going. 

Thinking about our current migration guides, do we imagine that content going under, `using existing devfiles` and/or `building devfiles for your project`? The current migration docs is to update and upgrade devfiles, so maybe some of the content would be used in the proposed existing devfiles or building devfiles section. 

I'm simply visualizing where we're imagining current content being housed in the future. If the proposed structure doesn't have a fit for our current docs, we can always add more sections accordingly. Thanks!

**Comment by rkratky** [comment]
JIRA issue: https://issues.redhat.com/browse/RHDEVDOCS-2940

**Comment by jc-berger** [comment]
Here is a Gdoc I've made. I simply added headings for our developer and registry admin persona, then added where we can add more registry docs, taken from John's repo.

https://docs.google.com/document/d/1OamiXqtwvWtdHKJRpqJ8HOULUOLlUQV0-uvoZHyp3G8/edit
