### ISSUE TITLE
improve test log messages 

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#505]
The format of test log message is messy and hard to maintain, for example
some pass/fail messages have leading spaces: 
https://github.com/devfile/api/blob/eb2947ee034c0275e6ef713f13feac962ab20f02/test/v200/schemaTest/schema_test.go#L64
some do not have leading spaces: 
https://github.com/devfile/api/blob/eb2947ee034c0275e6ef713f13feac962ab20f02/test/v200/schemaTest/schema_test.go#L71

some info messages have prefix of `.......`: 
https://github.com/devfile/api/blob/eb2947ee034c0275e6ef713f13feac962ab20f02/test/v200/utils/common/command_test_utils.go#L105
some have prefix of  `spaces + ......`:
https://github.com/devfile/api/blob/eb2947ee034c0275e6ef713f13feac962ab20f02/test/v200/utils/common/endpoint-test-utils.go#L52

and error has additional 5-dot prefix, which is kind of : https://github.com/devfile/api/blob/eb2947ee034c0275e6ef713f13feac962ab20f02/test/v200/utils/common/test_utils.go#L162-L163

We should create `logs.go` with `logErrorMessage` , `logInforMessage` to properly format the messages.

**Comment by kim-tsao** [comment]
It looks like the schema tests are to be replaced by the api tests according to this wiki:https://github.com/devfile/api/tree/main/test#apitest

Some messages have the leading `.......` prefix because it's for indentation purposes.  e.g. if you inspect the `test.log` output, the formatting makes a little more sense in this context. 
![image](https://user-images.githubusercontent.com/84398375/122938482-c9af2b00-d340-11eb-844f-1ef5b164d4ad.png)

We could look at refactoring the `logErrorMessage` and `logInfoMessage` functions out of `test_utils.go`

**Comment by yangcao77** [comment]
Even for indentation purposes, thoses leading spaces and `.......` need to be typed in manually for each particular message, and unclear on which kind of message should include those indentation. 
I'm thinking having common functions for logging purpose would help future maintenance.

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
