### ISSUE TITLE
Incorrect api version is generated from "go get github.com/devfile/api/v2@main" command

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#599]
/kind bug

### Which area this bug is related to?

/area api

## Bug Summary
**Describe the bug:**

When consumers pick up the latest api package that's under development, they typically run a `go get` command to update their go.mod file but the version that gets generated is `v2.0.0-<timestamp of last commit>`.  This looks out of date because it implies changes to the v2.0.0  spec when v2.1.0 is our latest.  This can cause  confusion since the underlying code is actually the latest.

## Expected behavior

We should ensure the version reflects the latest version that's under development

## Additional context

v2.0.0 is being generated because the main branch does not have any tags (these are associated with our release branches), so `go get` generates a pseudo version that's based on the version specified in the module path (v2).  

**Any workaround?**

**Suggestion on how to fix the bug**

Based on how pseudo-versions work, we may be able to correct this by adding pre-release tags to the api repo: https://golang.org/ref/mod#pseudo-versions

**Comment by yangcao77** [comment]
This issue affects pull in latest devfile/api to devfile/library. since library has dependency to registry-library, and registry-library currently uses devfile v2.2.0. when pull in `devfile/api/v2@main`, the version went back to `2.0.0-<timestamp>`, and go will think it's a downgrade, and will remove the registry-library module. 
```
$ go get github.com/devfile/api/v2@main
go: downgraded github.com/devfile/api/v2 v2.2.0 => v2.0.0-20230413012049-a6c32fca0dbd
go: removed github.com/devfile/registry-support/index/generator v0.0.0-20221018203505-df96d34d4273
go: removed github.com/devfile/registry-support/registry-library v0.0.0-20221018213054-47b3ffaeadba
```

I have created a pre-release tag:[v2.2.1-alpha]( https://github.com/devfile/api/releases/tag/v2.2.1-alpha), and the versioning functions well now. 

```
go get github.com/devfile/api/v2@a6c32fca0dbdcb61454e7bb7ff5b5ef525bbbe86
go: downloading github.com/devfile/api/v2 v2.2.1-alpha.0.20230413012049-a6c32fca0dbd
go: upgraded github.com/devfile/api/v2 v2.2.0 => v2.2.1-alpha.0.20230413012049-a6c32fca0dbd
```


we should continue this practice in future as well.
