### ISSUE TITLE
Devfile registry telemetry: the issue of tracking the number of users

### ISSUE THREAD

**Issue by GeekArthur** [devfile/api#638]
/kind bug

### Which area this bug is related to?

> /area registry

## What versions of software are you using?

**Operating System:** Any

**Go Pkg Version:** Latest

## Bug Summary
**Describe the bug:**

Below is the current "People" report from Woopra:

![image](https://user-images.githubusercontent.com/15131537/136315792-442e4dcd-934f-40c5-ad65-26d818092e2b.png)

The report is a little bit misleading, it would be better if "People" column is "Group". The ideal report would be each "People" has a unique IP so than we can count the number of users correctly as we use the unique IP as visitor id.

## Additional context

**Suggestion on how to fix the bug**

Given Woopra uses visitor id as an indicator to differentiate "People", to fix this I think probably we can use user's IP as visitor id then create another property called group to store the information of which group (eg.odo, anonymous) the user belongs to, then we can use Woopra filter to filter people by group

**Comment by kim-tsao** [comment]
Segment's Analytics.js package offers up a way to generate an anonymousID which can be stored in the users' browser but this capability is only available on client side calls which will include the Registry Viewer and Landing page.  The index server makes server side calls but we decided it may not be worthwhile to move rendering to the client side since we anticipate greater usage through the Registry Viewer.  We will continue to keep the generic IDs since those events, even though aggregated, may be of some value.

**Comment by kim-tsao** [comment]
Registry viewer issue: https://github.com/devfile/api/issues/678

**Comment by kim-tsao** [comment]
I think we can consider this done since we have a path forward to track individual, anonymous users which needs to be implemented on each client.  We can use the telemetry client issue https://github.com/devfile/api/issues/646 to track the remaining work
