### ISSUE TITLE
Ensure devfiles available on the registry are compatible with devworkspace

### ISSUE THREAD

**Issue by slemeur** [devfile/api#681]
The goal of this issue is to make sure that all the devfile that are provided in the registry are tested and made compatible with devworkspace and in line with #679

**Which area/kind this issue is related to?**
/area registry
/area devworkspace

Stacks fixes:
- [x] Use NON-terminating container components ([PR](https://github.com/devfile/registry/pull/102))
- [x] Replace `${PROJECTS_ROOT}` with `${PROJECT_SOURCE}` in commands `workingDir`
- [x] Replace hardcoded `/project(s)` with `${PROJECT_SOURCE}` in commands `workingDir`  ([PR](https://github.com/devfile/registry/pull/100))
- https://github.com/eclipse/che/issues/21389

Samples fixes:
- [x] Remove invalid `buildguidance` components
- [x] Some container components use a non existing image (e.g. `quay.io/eclipse/che-java11-maven:nightly`).
- [x] Use `schemaVersion` >= 2.1.0
- [x] Remove `projectStarter` and `project` from the Devfiles in a git repository
- [ ] Sync `devfile.yaml` published at `registry.devfile.io` and the ones in the git repositories
- [ ] Sync latest stacks and samples devfiles

**Comment by l0rd** [comment]
Che currently shows on its landing page a list of "Getting Started" projects. That's a list of GitHub repos or zip files **that have a devfile at their root**. It's important that Getting Started have a devfile at its root if we want to drive adoption of the devfile. And we are migrating all our "Getting Started" to be zip files because that provides better performances and support air-gap environment by default. 

To use the Devfile Registry as the source for Che "Getting Started" we could use the Devfile Registry "samples". But that may not be the best option (see below the problems for samples). The alternative is to use the Devfile Registry stacks. That means that, at Che build time, the Devfile Registry stacks are fetched and projects zip files are created. The zip files should include the stack devfile without the "projects" or "projectStarter" section. 

Anyway this is a list of problems that need to be addressed to adopt the Devfile Registry in Che:

General devfiles problems:
- Some container components use a terminating image (e.g. `registry.access.redhat.com/ubi8/nodejs-14:latest`), without specifying a non terminating command / args.
- Some `commands.exec.commandlLine` have the path harcoded to `/project`.  Special variables `$PROJECTS_ROOT` or `$PROJECT_SOURCE` should be used instead (those are mentioned in the API reference).
- Che getting started are currently using the Universal Developer Image
- We should contribute the Che "Getting Started" that are missing among the Devfile Registry stacks 
- We should contribute a Che / DevWorkspace test for PR check and CI

Specific samples problems:
- There are just 4 samples vs 30 in CRW/Che today.
- Devfiles include a `buildguidance` component that is invalid
- Some container components use a non existing image (e.g. `quay.io/eclipse/che-java11-maven:nightly`).
- Devfiles use spec 2.0.0 but Che requires >= 2.1.0
- Some devfiles have a `projectStarter` or `project` (but are already included in a project).
- `devfile.yaml` published at `registry.devfile.io` and the ones in the git repository are out of sync (maybe a change in the git repo happened after the build of the registry?).
- stacks and samples are out of sync

**Comment by kadel** [comment]
> * Some `commands.exec.commandlLine` use`$PROJECTS_ROOT` but `$PROJECTS_ROOT/<project-name>` should used instead.

This item can be problematic. Where would the `project-name` come from if there is no `project` section in devfile?

**Comment by l0rd** [comment]
That’s a good point Thomas. So after some thoughts this morning I concluded
that we should use $PROJECT_SOURCE in all single-project devfiles.

**Comment by l0rd** [comment]
I have updated my comment suggesting to use `$PROJECT_SOURCE`

**Comment by ibuziuk** [comment]
Closing. Starting from 7.82.0 Eclipse Che is going to use registry.devfile.io by default
