### ISSUE TITLE
default values on JSON schema 

### ISSUE THREAD

**Issue by gorkem** [devfile/api#74]
[devfile schema ](https://github.com/devfile/kubernetes-api/blob/master/schemas/devfile.json) should specify the default values for properties that have them.

**Comment by davidfestal** [comment]
Initially I had specified default values as `kube-builder` annotations and they automatically went into the  CRD OpenAPI schema. 

But then there was an error, since it was a very recent feature and still not supported by the whole operator-sdk / OLM toolchain at this point, which is why I removed them.

But in the meantime we could quite easily accommodate this limitation in the script that generates CRDs and schemas from the Go source code.
I'll look into this after coming back from my PTO week (next week).
