### ISSUE TITLE
mountsources default value for containers

### ISSUE THREAD

**Issue by gorkem** [devfile/api#75]
The default value for for `mountsources` should be `true` for all component types except for the plugin type.

**Comment by l0rd** [comment]
That's a good point because on the other end [we have discussed and agreed](https://github.com/devfile/kubernetes-api/issues/48) that the default value for `dedicatedPod` should be `true`. But `dedicatedPod: true` is compatible with `mountsources: true` only if the storage backend supports `RWX` OR if we use rsync to sync sources amongst pods.

**Comment by gorkem** [comment]
I see the point. Perhaps we should just state that if not explicitly defined all component will mountsources except plugin types and those that have `dedicatedPod` set to be `true`.

**Comment by johnmcollier** [comment]
Closed in https://github.com/devfile/api/pull/145
