### ISSUE TITLE
one `PullStackFromRregistry` call creates 3 events in telemetry

### ISSUE THREAD

**Issue by kadel** [devfile/api#933]
/kind bug

### Which area this bug is related to?

/area library
/area registry

## What versions of software are you using?

registry library version `36887a7907aa`

## Bug Summary

Using `PullStackFromRregistry` function from `github.com/devfile/registry-support/registry-library/library` to pull devfiles from the registry creates 3 events (two `download devfile` and one `list devfile`) in the telemetry.

```go
package main

import (
	"github.com/devfile/registry-support/registry-library/library"
)

func main() {
	td := library.TelemetryData{
		Client: "test-staging",
	}
	opts := library.RegistryOptions{
		Telemetry: td,
	}
	library.PullStackFromRegistry("https://registry.devfile.io", "nodejs-vue", ".", opts)
}
```

events recorded when the above call executed 
```
client.Track(&analytics.Track{
  UserId: "test-staging",
  Event: "list devfile",
  Properties: map[string]interface{}{
    "client": "test-staging",
    "registry": "devfile-community-registry",
    "type": "stack",
  },
})
```

```
client.Track(&analytics.Track{
  UserId: "test-staging",
  Event: "download devfile",
  Properties: map[string]interface{}{
    "client": "test-staging",
    "name": "nodejs-vue",
    "registry": "devfile-community-registry",
  },
})
```

```
client.Track(&analytics.Track{
  UserId: "test-staging",
  Event: "download devfile",
  Properties: map[string]interface{}{
    "client": "test-staging",
    "name": "nodejs-vue",
    "registry": "devfile-community-registry",
  },
})
```

## Expected behavior

I would expect that calling `PullStackFromRegistry` creates just one `download devfile` event and nothing else 

Target Date: 2022-11-04

**Comment by kim-tsao** [comment]
The `List Devfile` call is due to the fact that a request is made in the `PullStackFromRegistry` function to retrieve the registry index.  Since this is an internal call, I can add an identifier to ensure those events get filtered out.  

The two download events are expected because our stacks have 2 resources; an archive and an devfile.yaml
see https://registry.devfile.io/index

    "resources": [
      "archive.tar",
      "devfile.yaml"
    ],
 
When we make an oras call to copy the content, it goes through each supported media type and retrieves the associated resource which results in 2 download requests but the archive.tar does not contain anything useful (just the OWNERS file).   I can filter out this file so an archive does not get created from it.  That way, the stacks will only have the one devfile.yaml resource.

**Comment by kim-tsao** [comment]
Fix is now in production.  I verified I only see one download event using the test snippet above.
